---
title: "Senator_Voting_Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r libraries}
library(dplyr)
library(ggplot2)
library(tidyverse)
```




```{r data}
senator_party <- read.csv(file="senator_party.csv")
senator_votes_1 <- read.csv(file="senator_votes_113-1.csv")
senator_votes_2 <- read.csv(file="senator_votes_113-2.csv")
senators <- read.csv(file="senator.csv")
result_code <- read.csv(file="result_code_list.csv")
tally_code <- read.csv(file="tally_code_list.csv")

regions_data <- read.csv(file="regions_data.csv")
regions_description <- read.csv(file="regions_description.csv")

regions_data <- subset(regions_data, id_regions_description != 5)
```

```{r combine table}

vote_table <- select(senator_votes_1,voteno,member_code,tally_code) %>%
  filter(tally_code %in% c("A","B"))

vote_table$tally_code = ifelse(vote_table$tally_code=="A",0,1)

party_votes <- left_join(vote_table,select(senator_party,member_code,caucus_with), by = "member_code") 

party_votes

party_vote_count <- party_votes %>%
  select(voteno, caucus_with, tally_code) %>%
  group_by(voteno, caucus_with) %>%
  mutate( total_party_votes = sum(voteno)/voteno ) %>%
  group_by(voteno, caucus_with, total_party_votes) %>%
  summarise( total_party_support = sum(tally_code) )

party_vote_count <- party_vote_count %>%
  mutate( avg_party_support = total_party_support/total_party_votes)

party_vote_count
  

party_support_difference <- select(party_vote_count,voteno,caucus_with,avg_party_support) %>%
  spread(key = caucus_with, value = avg_party_support) %>%
  mutate( difference = D-R )

party_support_difference



name_votes <- left_join(party_votes,select(senators,member_code,print_name,state_code), by = "member_code")

name_votes <- left_join(name_votes,select(regions_data,state_code,id_regions_description), by = "state_code")

name_votes <- left_join(name_votes,select(regions_description,id_regions_description,title), by = "id_regions_description")

#name_votes


group_votes <- select(name_votes,voteno,tally_code,caucus_with) %>%
  group_by(caucus_with) %>%
  summarise( total = sum(tally_code) )

#group_votes


```



```{r plot party support}

party_support_differenceD <- party_support_difference[order(party_support_difference$D),] %>%
  rowid_to_column()

party_support_differenceR <- party_support_difference[order(party_support_difference$R),] %>%
  rowid_to_column()

party_support_differenceD

party_support_differenceR %>% ggplot() + geom_point( aes( x=as.factor(rowid), y=D), color="blue") + geom_point( aes( x=as.factor(rowid), y=R), color="red") + xlab("Vote") + ylab("Party Support")

#party_support_difference2 %>% ggplot( ) + geom_point( aes( x=voteno, y=D ), color="blue") + geom_point( aes( x=voteno, y=R ), color="red") + xlab("Vote Number") + ylab("Party Support")

party_support_difference %>% ggplot( ) + geom_point( aes(x=voteno, y=difference), color="green")

```

```{r plot regions support}

region_votes <- select(name_votes,voteno,print_name,tally_code,title)

region_vote_count <- region_votes %>%
  group_by(voteno, title) %>%
  mutate( total_region_votes = sum(voteno)/voteno ) %>%
  group_by(voteno, title, total_region_votes) %>%
  summarise( total_region_support = sum(tally_code) )

region_vote_count <- region_vote_count %>%
  mutate( avg_region_support = total_region_support/total_region_votes)

region_vote_count


region_support_difference <- select(region_vote_count,voteno,title,avg_region_support) %>%
  spread(key = title, value = avg_region_support)

region_support_difference


region_support_differenceNE <- region_support_difference[order(region_support_difference$Northeast),] %>%
  rowid_to_column()

region_support_differenceS <- region_support_difference[order(region_support_difference$South),] %>%
  rowid_to_column()

region_support_differenceW <- region_support_difference[order(region_support_difference$West),] %>%
  rowid_to_column()

region_support_differenceMW <- region_support_difference[order(region_support_difference$Midwest),] %>%
  rowid_to_column()



region_support_difference %>% ggplot() + geom_point( aes( x=voteno, y=Northeast), color="blue") + geom_point( aes(x=voteno, y=South), color="red") + geom_point( aes(x=voteno, y=Midwest), color="gold") + geom_point( aes(x=voteno, y=West), color="green") + xlab("Vote") + ylab("Region Support")


region_support_differenceNE %>% ggplot() + geom_point( aes( x=as.factor(rowid), y=Northeast), color="blue") + geom_point( aes(x=as.factor(rowid), y=South), color="red") + geom_point( aes(as.factor(rowid), y=Midwest), color="gold") + geom_point( aes(as.factor(rowid), y=West), color="green") + xlab("Vote") + ylab("Region Support")

region_support_differenceS %>% ggplot() + geom_point( aes( x=as.factor(rowid), y=Northeast), color="blue") + geom_point( aes(x=as.factor(rowid), y=South), color="red") + geom_point( aes(as.factor(rowid), y=Midwest), color="gold") + geom_point( aes(as.factor(rowid), y=West), color="green") + xlab("Vote") + ylab("Region Support")

region_support_differenceW %>% ggplot() + geom_point( aes( x=as.factor(rowid), y=Northeast), color="blue") + geom_point( aes(x=as.factor(rowid), y=South), color="red") + geom_point( aes(as.factor(rowid), y=Midwest), color="gold") + geom_point( aes(as.factor(rowid), y=West), color="green") + xlab("Vote") + ylab("Region Support")

region_support_differenceMW %>% ggplot() + geom_point( aes( x=as.factor(rowid), y=Northeast), color="blue") + geom_point( aes(x=as.factor(rowid), y=South), color="red") + geom_point( aes(as.factor(rowid), y=Midwest), color="gold") + geom_point( aes(as.factor(rowid), y=West), color="green") + xlab("Vote") + ylab("Region Support")



```


```{r consitency}

support_totals <- left_join(region_support_difference,select(party_support_difference,voteno,D,R), by = "voteno")

#support_totals

senator_consistency <- select(name_votes,member_code,print_name,caucus_with,state_code,title) %>%
  group_by(member_code,print_name,caucus_with,state_code,title) %>% summarise()

#senator_consistency


senator_consistency %>% mutate(consist_D = -1, consist_R = -1, consist_NE = -1, consist_S = -1, consist_MW = -1, consist_W = -1 )



for( name in senator_consistency$print_name ){
  
  name_index <- which(senator_consistency$print_name == name)
  
  local_senator_consistency <- filter(name_votes, print_name == name) %>%
  left_join(support_totals, by = "voteno")
  
  
  senator_consistency[name_index, "consist_D"] <- ( 1 - mean( abs( local_senator_consistency$D - local_senator_consistency$tally_code ) ) )
  
  senator_consistency[name_index, "consist_R"] <- ( 1 - mean( abs( local_senator_consistency$R - local_senator_consistency$tally_code ) ) )
  
  senator_consistency[name_index, "consist_NE"] <- ( 1 - mean( abs( local_senator_consistency$Northeast - local_senator_consistency$tally_code ) ) )
  
  senator_consistency[name_index, "consist_S"] <- ( 1 - mean( abs( local_senator_consistency$South - local_senator_consistency$tally_code ) ) )
  
  senator_consistency[name_index, "consist_MW"] <- ( 1 - mean( abs( local_senator_consistency$Midwest - local_senator_consistency$tally_code ) ) )
  
  senator_consistency[name_index, "consist_W"] <- ( 1 - mean( abs( local_senator_consistency$West - local_senator_consistency$tally_code ) ) )
  
  
}

#senator_consistency

senator_consistency <- mutate(senator_consistency, name_state = paste(print_name," (",caucus_with,"-",state_code,")", sep="") )

senator_consistency


ShelbyD <- which(senator_consistency$print_name == "Shelby" & senator_consistency$caucus_with == "D" )

senator_consistency <- senator_consistency[-ShelbyD,]

colnames(senator_consistency)[colnames(senator_consistency)=="caucus_with"] <- "party"

 

senator_consistency


```


```{r bar charts}

party.colors = c(D='blue', R='red')

senator_consistency %>% ggplot( mapping=aes( x=reorder(name_state, -consist_D), y=consist_D, fill=party) ) + geom_bar( stat="identity") + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=1)) + scale_fill_manual(values=party.colors) + ggtitle("Alignment with D") + xlab("Senator") + ylab("Consistency with Average D Votes") + ylim(0,1)

senator_consistency %>% ggplot( mapping=aes( x=reorder(name_state, -consist_R), y=consist_R, fill=party) ) + geom_bar( stat="identity") + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=1)) + scale_fill_manual(values=party.colors) + ggtitle("Alignment with R") + xlab("Senator") + ylab("Consistency with Average R Votes") + ylim(0,1)

senator_consistency %>% ggplot( mapping=aes( x=reorder(name_state, -consist_NE), y=consist_NE, fill=party) ) + geom_bar( stat="identity") + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=1)) + scale_fill_manual(values=party.colors) + ggtitle("Alignment with Northeast") + xlab("Senator") + ylab("Consistency with Average NE Votes") + ylim(0,1)

senator_consistency %>% ggplot( mapping=aes( x=reorder(name_state, -consist_S), y=consist_S, fill=party) ) + geom_bar( stat="identity") + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=1)) + scale_fill_manual(values=party.colors) + ggtitle("Alignment with South") + xlab("Senator") + ylab("Consistency with Average S Votes") + ylim(0,1)

senator_consistency %>% ggplot( mapping=aes( x=reorder(name_state, -consist_MW), y=consist_MW, fill=party) ) + geom_bar( stat="identity") + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=1)) + scale_fill_manual(values=party.colors) + ggtitle("Alignment with Midwest") + xlab("Senator") + ylab("Consistency with Average MW Votes") + ylim(0,1)

senator_consistency %>% ggplot( mapping=aes( x=reorder(name_state, -consist_W), y=consist_W, fill=party) ) + geom_bar( stat="identity") + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=1)) + scale_fill_manual(values=party.colors) + ggtitle("Alignment with West") + xlab("Senator") + ylab("Consistency with Average W Votes") + ylim(0,1)


```



